### PR TITLE
Add Randomization Mode

### PR DESCRIPTION
**Pull request by coopeeo**
This Pull Request adds:
- Randomization Mode!

Recommend Squashing and merging this if you do merge.

### CODE REVIEW

**Comment by coopeeo** [comment]
wait letme edit one thing

**Comment by coopeeo** [comment]
im an impatiant human

**Comment by coopeeo** [comment]
Please review @iristraa i'm impatient

**Comment by iristraa** [comment]
merged oh my god it took me a month to review

**Comment by iristraa** [comment]
next update gonna add a lot of things to the table however

**Pull request merged**
